#!/bin/bash

if [ -f ~/.git-completion.bash -a -f ~/.git-prompt.sh ]; then
  source ~/.git-completion.bash
  source ~/.git-prompt.sh
  export GIT_PS1_SHOWDIRTYSTATE=1
  export GIT_PS1_SHOWSTASHSTATE=1
  export GIT_PS2_SHOWUNTRACKEDFILES=true
  export GIT_PS1_SHOWUPSTREAM="auto"
  export GIT_PS1_HIDE_IF_PWD_IGNORED=true
  export GIT_PS1_SHOWCOLORHINTS=1
  PROMPT_COMMAND='__git_ps1 "[\u@\h]:\w" "\\\$ "'
fi